Add multi include path feature for bundling c++ code
online-judge-tools/verification-helper pull request #336
Opened 2020-10-27 13:10 UTC by kjnh10

#298 の機能、自分で使いたかったのでとりあえずコードを修正してみましたがどうでしょうか。

とりあえず手元で複数の-Iオプション付きでbundleが正しく実行される事は確認しています。
該当のissueはざっと目を通しましたが分かってない部分も多く良い実装になってるかはよく分かりません。

またac-libraryに関しては（自作ライブラリについても同様ですが）expander.pyで展開出来る呼び出し方法を展開できないので少し修正した方が良いかもしれません。
#include <atcoder/fenwicktree>        ->  展開されない。 <>を展開しないのはおそらく仕様ですよね？
 #include "atcoder/fenwicktree"         -> 展開されない。 拡張子がないとg++のpreprocessが走らないようです。
#include "atcoder/fenwicktree.hpp"   -> この形式であれば展開される事は確認しました。

2020-10-28 11:21 UTC, kmyk requested changes
基本的にはよさそうです。しかし CI が落ちているとマージはできないので、修正お願いします。

- 必須: CI が落ちてるので直してください。手元で `yapf --inplace --recursive onlinejudge_verify onlinejudge_bundle` とかすれば自動で直してくれます。(<https://github.com/online-judge-tools/verification-helper/pull/336/checks?check_run_id=1314831412>)
- 省略可: 可能ならテストを足してくれるとうれしいです。(<https://github.com/online-judge-tools/verification-helper/blob/master/tests/test_bundle.py>)

2020-10-28 11:36 UTC, kmyk commented
> またac-libraryに関しては（自作ライブラリについても同様ですが）expander.pyで展開出来る呼び出し方法を展開できないので少し修正した方が良いかもしれません。

これは重要な指摘ですね。これは気付いていませんでした。

- `#include <atcoder/fenwicktree.hpp>` が展開されないのは仕様です。競プロ用途ならこれは妥当な仕様だと考えていますが、不便だと感じるユーザが多いなら ac-library 専用に特殊なオプションを足すなどはありだとは思います。
- `#include "atcoder/fenwicktree"` が展開されないのはバグです。これはかなり不便なので、はやめに直しておくべきでしょう。

@kjnh10 このふたつについて issue を建てておくのを任せていいですか？

2020-10-28 13:26 UTC, kjnh10 commented
yapfのcheckは問題なくなった気がするのですが今度はmypyのチェックで落ちてそうなので確認してみます。
あとテストも追加してみますね。

#includeの形式に関しては多分出来ると思います。詳細は別のissueで相談させてもらえればと思います。

2020-10-28 13:29 UTC, kjnh10 commented on onlinejudge_verify/languages/cplusplus.py
> +    def bundle(self, path: pathlib.Path, *, basedir: pathlib.Path=pathlib.Path.cwd(), options: Dict[str, Any]) -> bytes:
assert isinstance(options['include_paths'], list)を190行目に追加する感じでよいでしょうか？

2020-10-28 13:50 UTC, kmyk commented on onlinejudge_verify/languages/cplusplus.py
> +    def bundle(self, path: pathlib.Path, *, basedir: pathlib.Path=pathlib.Path.cwd(), options: Dict[str, Any]) -> bytes:
はい。
ついでに `include_paths: List[pathlib.Path] = options['include_paths']` として変数に置いてくれるとうれしいです。(よく考えると、`assert isinstance(include_path, list)` だけだと何のリストなのかがはっきりしないので)

2020-10-28 15:33 UTC, kjnh10 commented
complicatedのテストを少し修正する形でテストを追加してみましたがいかがでしょうか。
unittestで追加するか迷いましたが一番楽そうだったので、、

2020-10-28 15:54 UTC, kjnh10 commented on onlinejudge_verify/documentation/build.py
> +        bundled_code = language.bundle(stat.path, basedir=basedir, options={'include_paths': [basedir]}).decode()
mypyのチェックでoptionがないと言われたため、C++のコードが正しく展開されるような値を渡すようにしてみましたがこれでいいのか確信はないです。

あとそもそもbundleの引数であるbasedirが全く使われないようになっている（今回の変更で）ので引数から削除した方がよいでしょうか？C++以外のためには残しておいた方がいいのかもしれませんがそもそもbasedirが何のための変数か把握出来ておらずです。

2020-11-02 13:29 UTC, kmyk approved these changes
LGTM
細かい指摘はいくつかあります。直してもらってもよいですし、無視してこのまま merge することにしてもらってもよいです。

(返事が遅れてしまってごめんなさい)

2020-11-02 13:29 UTC, kmyk commented on onlinejudge_verify/documentation/build.py
> +        bundled_code = language.bundle(stat.path, basedir=basedir, options={'include_paths': [basedir]}).decode()
nitpick:

> mypyのチェックでoptionがないと言われたため、C++のコードが正しく展開されるような値を渡すようにしてみましたがこれでいいのか確信はないです。

「そのコードがどのように動作するか」の意味では、これで大丈夫です。正しく動作すると思います。
「そのコードがどのように書かれているか」の意味では、すこし不満です。「`options` に `{'include_paths': [basedir]}` を渡す」というのは C++ のファイル専用の特殊な処理であり、ここは本来は言語ごとに分岐して `options` を選択する処理があるはずです。しかし現在はそれが省略して書かれていまず。今後の混乱を防ぐため、省略されたことがそうと分かるようなコメントを書いておいてほしいです


---

`basedir` は `.verify-helper/` のあるディレクトリを指します。
「`.verify-helper/` がカレントディレクトリに存在すること」を仮定するべきではないので「`.verify-helper/` があるディレクトリ」の情報を引数で渡す必要があります。たとえば git コマンドは `.git/` のあるディレクトリ以外でも実行できますが、これと同様に `oj-verify` も `.verify-helper/` があるディレクトリ以外でも実行できるべきなためです (https://github.com/online-judge-tools/verification-helper/issues/128 )。

2020-11-02 13:29 UTC, kmyk commented on onlinejudge_verify/languages/cplusplus.py
> +        bundler = Bundler(iquotes=include_paths)
:+1:

2020-11-02 13:29 UTC, kmyk commented on onlinejudge_verify/languages/user_defined.py
> +    def bundle(self, path: pathlib.Path, *, basedir: pathlib.Path, options: Dict[str, Any] = None) -> bytes:
nitpick: ここの `= None` はなにか奇妙です。いろいろあって型エラーではないとはいえ、辞書型のはずの変数に `None` を入れるのはなんとなく嫌な感じがします。
`options` の中身を使わないことを明示したいのなら、`assert options == {}` と書く方が適切でしょう。

2020-11-02 13:29 UTC, kmyk commented on tests/test_bundle.py
> +            subprocess.check_call(['g++', str(tempdir_dst / 'main.bundled.cpp')], stderr=sys.stderr)
nitpick: ファイル末尾の改行が削除されてしまってます。無関係な修正を混入させるべきではないので、改行を足しておいてほしいです

なお、pylint などでエラーになってないのはこちらの設定が悪いです :bow:

2020-11-02 13:29 UTC, kmyk commented on tests/test_bundle.py
> +        library_files_1 = {
:+1:
テスト追加ありがとう

2020-11-03 10:41 UTC, kjnh10 commented
簡単なところだけ直してみましたのでこれでマージをお願いしてもよろしいでしょうか？

コメント追加のあたりは趣旨は理解しましたが適切なコメントを書けるか不安なので。また細かく指摘して頂くのも申し訳ないですし、、

2020-11-03 15:29 UTC, kmyk commented
了解です。ではこのままマージします。
プルリクありがとうございました。

2020-11-03 15:29 UTC, merged

2020-11-03 15:34 UTC, kmyk commented
@kjnh10 バージョンの更新は #340 が修正された後でやろうと思っています。もし早めの更新が必要なら伝えてください